### ISSUE TITLE
Please show a few images on the main README

### ISSUE THREAD

**Issue by rubyFeedback** [D2-mods/The-Workshop-Kitpack#19]
Hey there,

Just found the mod kind of accidentally.

As I don't know it yet, could you perhaps consider showing one overview image?

This image does not need to show everything, but perhaps 1-3 or 3-5 items or so,
and perhaps one or two kits, if they have images available. A bit of a teaser, like
how the Dusk NPC mod showcases some of the items and main NPC character
there used upon. Thakn you for potentially considering this issue request.

**Comment by D2-mods** [comment]
Hi, what I'll say is I'll think about it. I looked up the Dusk NPC mod, since I wasn't familiar with it. The Github page shows a fancy main image, which I don't have the skill to do. The post on the Beamdog forums shows a few screenshots, and the main one that stands out is the one showing Dusk's portrait (obviously not an option for this mod). The others are pretty generic screens.

Was there something you were unsure about from the readme? Note that the readme includes all kit and item descriptions, and the top section has a summary of all contents. Adding images seems mainly useful to make the page more attractive (not a bad thing, it's just not something I care too much about). The way I do readmes, it's mainly about getting the technical details and compat info on the page.

Note: This isn't mentioned in the readme, but the mod also adds the item resource "d2#hbag". This is a bag of holding containing all items from this mod (other than holy symbols). This is meant for dev work, but can be used as a quick way to see all items in-game, if you mainly want to see how they work.

**Comment by D2-mods** [comment]
Added one small preview image (just some screens cut up and pasted together). Might add something lower down later, but I think for now this is fine. I'll consider this issue resolved.
